name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  infra-validate:
    name: Validate Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install infra-validator deps
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install gitpython pydantic pydantic-settings redis httpx setuptools

      - name: Run infra validation (skip service checks)
        run: |
          source venv/bin/activate
          python Dev/idvc-project/infra_validation.py --skip-service-checks

  test:
    name: Run Connector Tests
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379
    needs: infra-validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install app deps & pytest
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r Dev/idvc-project/requirements.txt pytest

      - name: Run pytest
        run: |
          source venv/bin/activate
          pytest -q Dev/idvc-project/tests

  docker-build:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_NAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: Dev/idvc-project
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/idvc:${{ github.sha }}

  deploy:
    name: Deploy to Azure Web App
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy container to Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          images: ${{ secrets.ACR_NAME }}.azurecr.io/idvc:${{ github.sha }}
